'use strict';

class FlightsService {
    
    constructor(){
        'ngInject';
        this.airportRealNames = { '0AK': 'Pilot Station Airport',
        '16A': 'Nunapitchuk Airport',
        '1G4': 'Grand Canyon West Airport',
        '2A3': 'Larsen Bay Airport',
        '2A9': 'Kotlik Airport',
        '3A5': 'Marshall Don Hunter Sr',
        '3T7': 'Middle Bass Island Airport',
        '3W2': 'Put - in - Bay Airport',
        '6R7': 'Old Harbor Airport',
        '74S': 'Anacortes Airport',
        A61: 'Tuntutuliak Airport',
        A85: 'Kwigillingok Airport',
        ABE: 'Lehigh Valley International Airport',
        ABI: 'Abilene Regional Airport',
        ABQ: 'Albuquerque International Sunport',
        ABR: 'Aberdeen Regional Airport',
        ABY: 'Southwest Georgia Regional Airport',
        ACB: 'Bellaire/Antrim County Airport',
        ACK: 'Nantucket Memorial Airport',
        ACT: 'Waco Regional Airport',
        ACV: 'Arcata Airport',
        ACY: 'Atlantic City International Airport',
        ADK: 'Adak Airport',
        ADQ: 'Kodiak Airport',
        AEX: 'Alexandria International Airport',
        AFM: 'Ambler Airport',
        AGC: 'Allegheny County Airport',
        AGN: 'Angoon Seaplane Base',
        AGS: 'Augusta Regional Airport',
        AHN: 'Athens/Ben Epps Airport',
        AIA: 'Alliance Municipal Airport',
        AID: 'Anderson Municipal Airport',
        AIY: 'Atlantic City Municipal Airport/Bader Field',
        AIZ: 'Lee C Fine Memorial Airport',
        AKN: 'King Salmon Airport',
        AKP: 'Anaktuvuk Pass Airport',
        AKW: 'Klawock Airport',
        ALB: 'Albany International Airport',
        ALM: 'Alamogordo-White Sands Regional Airport',
        ALN: 'St Louis Regional Airport',
        ALO: 'Waterloo Regional Airport',
        ALS: 'San Luis Valley Regional Airport',
        ALW: 'Walla Walla Regional Airport',
        AMA: 'Amarillo International Airport',
        ANB: 'Anniston Municipal Airport',
        ANC: 'Anchorage International Airport',
        AND: 'Anderson Regional Airport',
        ANI: 'Aniak Airport',
        AOO: 'Altoona-Blair County Airport',
        APF: 'Naples Municipal Airport',
        APN: 'Alpena County Regional Airport',
        AQH: 'Quinhagak Airport',
        AQT: 'Nuiqsut Airport',
        ART: 'Watertown International Airport',
        ASE: 'Aspen-Pitkin County Airport',
        ASN: 'Talladega Municipal Airport',
        AST: 'Astoria Regional Airport',
        ATK: 'Atqasuk Edward Burnell Sr Memorial Airport',
        ATL: 'Atlanta International Airport',
        ATW: 'Outagamie County Regional Airport',
        ATY: 'Watertown Municipal Airport',
        AUG: 'Augusta State Airport',
        AUK: 'Alakanuk Airport',
        AUS: 'Austin-Bergstrom International Airport',
        AVL: 'Asheville Regional Airport',
        AVP: 'Wilkes-Barre/Scranton International Airport',
        AWI: 'Wainwright Airport',
        AXN: 'Chandler Field Airport',
        AZO: 'Kalamazoo/Battle Creek International Airport',
        BAF: 'Barnes Municipal Airport',
        BAK: 'Columbus Municipal Airport',
        BCE: 'Bryce Canyon Airport',
        BDE: 'Baudette International Airport',
        BDL: 'Bradley International Airport',
        BDR: 'Igor I Sikorsky Memorial Airport',
        BED: 'Bedford Hanscom Field',
        BEH: 'Southwest Michigan Regional Airport',
        BET: 'Bethel Airport',
        BFD: 'Bradford Regional Airport',
        BFF: 'Western Nebraska Regional Airport',
        BFI: 'Boeing Field/King County International Airport',
        BFL: 'Meadows Field Airport',
        BGM: 'Greater Binghamton Airport',
        BGR: 'Bangor International Airport',
        BHB: 'Hancock County-Bar Harbor Airport',
        BHM: 'Birmingham International Airport',
        BID: 'Block Island State Airport',
        BIG: 'Allen Aaf Airport',
        BIL: 'Billings Logan International Airport',
        BIS: 'Bismarck Municipal Airport',
        BJI: 'Bemidji Regional Airport',
        BKL: 'Burke Lakefront Airport',
        BKW: 'Raleigh County Memorial Airport',
        BKX: 'Brookings Municipal Airport',
        BLI: 'Bellingham International Airport',
        BLM: 'Monmouth Executive Airport',
        BLV: 'Midamerica Airport',
        BMG: 'Monroe County Airport',
        BMI: 'Central Illinois Regional Airport',
        BNA: 'Nashville International Airport',
        BOI: 'Boise Airport',
        BOS: 'Boston Logan International Airport',
        BPK: 'Baxter County Regional Airport',
        BPT: 'Southeast Texas Regional Airport',
        BQK: 'Brunswick Golden Isles Airport',
        BQN: 'Aguadilla Airport',
        BRD: 'Brainerd Lakes Regional Airport',
        BRL: 'Southeast Iowa Regional Airport',
        BRO: 'Brownsville/South Padre Island International Airport',
        BRW: 'Wiley Post-Will Rogers Memorial Airport',
        BTI: 'Barter Island LRRS Airport',
        BTL: 'W K Kellogg Airport',
        BTM: 'Bert Mooney Airport',
        BTR: 'Baton Rouge International Airport',
        BTV: 'Burlington International Airport',
        BUF: 'Buffalo Niagara International Airport',
        BUR: 'Burbank Bob Hope Airport',
        BVK: 'Buckland Airport',
        BWG: 'Bowling Green-Warren County Regional Airport',
        BWI: 'Baltimore / Washington International Airport',
        BZN: 'Bozeman Gallatin Field Airport',
        CAE: 'Columbia Metropolitan Airport',
        CAK: 'Akron-Canton Airport',
        CCR: 'Buchanan Field Airport',
        CDB: 'Cold Bay Airport',
        CDC: 'Cedar City Regional Airport',
        CDV: 'Cordova Municipal Airport',
        CDW: 'Essex County Airport',
        CEC: 'Jack Mc Namara Field Airport',
        CEF: 'Westover Metropolitan Airport',
        CEZ: 'Cortez Municipal Airport',
        CFK: 'Chefornak Airport',
        CGA: 'Craig Airport',
        CGF: 'Cuyahoga County Airport',
        CGI: 'Cape Girardeau Regional Airport',
        CGX: 'Merrill C Meigs Field',
        CHA: 'Chattanooga Metropolitan Airport',
        CHO: 'Charlottesville-Albemarle Airport',
        CHS: 'Charleston International Airport',
        CIC: 'Chico Municipal Airport',
        CID: 'Cedar Rapids Eastern Iowa Airport',
        CIU: 'Chippewa County International Airport',
        CKB: 'Harrison/Marion Regional Airport',
        CLE: 'Cleveland Hopkins International Airport',
        CLL: 'Easterwood Airport',
        CLM: 'William R Fairchild International Airport',
        CLT: 'Charlotte/Douglas International Airport',
        CMH: 'Port Columbus International Airport',
        CMI: 'Champaign Willard Airport',
        CMX: 'Houghton County Memorial Airport',
        CNM: 'Cavern City Air Terminal',
        CNY: 'Canyonlands Field',
        COD: 'Yellowstone Regional Airport',
        COE: 'Coeur D\'alene Airport',
        COS: 'Colorado Springs Airport',
        COU: 'Columbia Regional Airport',
        CPR: 'Natrona County International Airport',
        CPX: 'Culebra Airport',
        CRP: 'Corpus Christi International Airport',
        CRQ: 'Mc Clellan-Palomar Airport',
        CRW: 'Charleston Yeager Airport',
        CSG: 'Columbus Metropolitan Airport',
        CVG: 'Cincinnati / Northern Kentucky International Airport',
        CVO: 'Corvallis Municipal Airport',
        CVX: 'Charlevoix Municipal Airport',
        CWA: 'Central Wisconsin Airport',
        CWI: 'Clinton Municipal Airport',
        CYS: 'Cheyenne Regional Airport',
        D76: 'Robert (Bob) Curtis Memorial Airport',
        DAB: 'Daytona Beach International Airport',
        DAL: 'Dallas Love Field',
        DAN: 'Danville Regional Airport',
        DAY: 'Dayton International Airport',
        DBQ: 'Dubuque Regional Airport',
        DCA: 'Ronald Reagan Washington National Airport',
        DDC: 'Dodge City Regional Airport',
        DDH: 'William H. Morse State Airport',
        DEC: 'Decatur Airport',
        DEN: 'Denver International Airport',
        DET: 'Detroit City Airport',
        DFW: 'Dallas/Fort Worth International Airport',
        DHN: 'Dothan Regional Airport',
        DIK: 'Dickinson - Theodore Roosevelt Regional Airport',
        DLG: 'Dillingham Airport',
        DLH: 'Duluth International Airport',
        DNV: 'Vermilion County Airport',
        DRO: 'Durango-La Plata County Airport',
        DRT: 'Del Rio International Airport',
        DSM: 'Des Moines International Airport',
        DTW: 'Detroit Metro Airport',
        DUJ: 'Du Bois-Jefferson County Airport',
        DUT: 'Unalaska Airport',
        DUY: 'Kongiganak Airport',
        DVL: 'Devils Lake Municipal Airport',
        DVT: 'Deer Valley Municipal Airport',
        DXR: 'Danbury Municipal Airport',
        EAR: 'Kearney Municipal Airport',
        EAT: 'Pangborn Memorial Airport',
        EAU: 'Chippewa Valley Regional Airport',
        EEK: 'Eek Airport',
        EEN: 'Keene/Dillant-Hopkins Airport',
        EFD: 'Ellington Field',
        EFK: 'Newport State Airport',
        EGE: 'Eagle County Regional Airport',
        EKM: 'Elkhart Municipal Airport',
        EKO: 'Elko Regional Airport',
        ELI: 'Elim Airport',
        ELM: 'Elmira / Corning Regional Airport',
        ELO: 'Ely Municipal Airport',
        ELP: 'El Paso International Airport',
        ELY: 'Ely Airport',
        ENA: 'Kenai Municipal Airport',
        ENM: 'Emmonak Airport',
        ENW: 'Kenosha Regional Airport',
        ERI: 'Erie International Airport',
        ESC: 'Delta County Airport',
        ESF: 'Esler Regional Airport',
        EUG: 'Eugene Airport',
        EVV: 'Evansville Regional Airport',
        EWB: 'New Bedford Regional Airport',
        EWN: 'Craven County Regional Airport',
        EWR: 'Newark Liberty International Airport',
        EWU: 'Newtok Airport',
        EYW: 'Key West International Airport',
        FAI: 'Fairbanks International Airport',
        FAQ: 'Fitiuta Airport',
        FAR: 'Hector International Airport',
        FAT: 'Fresno Air Terminal',
        FAY: 'Fayetteville Regional/Grannis Field Airport',
        FHR: 'Friday Harbor Airport',
        FHU: 'Sierra Vista Municipal Airport',
        FKL: 'Venango Regional Airport',
        FLG: 'Flagstaff Pulliam Airport',
        FLL: 'Fort Lauderdale Hollywood International Airport',
        FLO: 'Florence Regional Airport',
        FMN: 'Four Corners Regional Airport',
        FNL: 'Fort Collins-Loveland Municipal Airport',
        FNT: 'Bishop International Airport',
        FOD: 'Fort Dodge Regional Airport',
        FOE: 'Forbes Field Airport',
        FRG: 'Republic Airport',
        FRM: 'Fairmont Municipal Airport',
        FSD: 'Sioux Falls Regional Airport',
        FSM: 'Fort Smith Airport',
        FTW: 'Fort Worth Meacham International Airport',
        FWA: 'Fort Wayne International Airport',
        FYU: 'Fort Yukon Airport',
        FYV: 'Drake Field',
        GAL: 'Edward G. Pitka Sr Airport',
        GAM: 'Gambell Airport',
        GBD: 'Great Bend Municipal Airport',
        GBH: 'Galbraith Lake Airport',
        GCC: 'Gillette-Campbell County Airport',
        GCK: 'Garden City Regional Airport',
        GCN: 'Grand Canyon National Park Airport',
        GED: 'Sussex County Airport',
        GEG: 'Spokane International Airport',
        GFK: 'Grand Forks International Airport',
        GFL: 'Floyd Bennett Memorial Airport',
        GGG: 'East Texas Regional Airport',
        GGV: 'Kwigillingok Airport',
        GGW: 'Wokal Field/Glasgow International Airport',
        GJT: 'Walker Field Airport',
        GKN: 'Gulkana Airport',
        GLD: 'Goodland Municipal Airport',
        GLH: 'Mid Delta Regional Airport',
        GLR: 'Gaylord Regional Airport',
        GLS: 'Galveston/Scholes International Airport',
        GNV: 'Gainesville Regional Airport',
        GON: 'Groton-New London Airport',
        GPI: 'Glacier Park International Airport',
        GPT: 'Gulfport-Biloxi International Airport',
        GPZ: 'Grand Rapids/Itasca County Airport',
        GRB: 'Austin Straubel International Airport',
        GRI: 'Central Nebraska Regional Airport',
        GRK: 'Killeen-Fort Hood Regional Airport',
        GRO: 'Rota International Airport',
        GRR: 'Gerald R. Ford International Airport',
        GSN: 'Saipan International Airport',
        GSO: 'Piedmont Triad International Airport',
        GSP: 'Greenville / Spartanburg Airport',
        GST: 'Gustavus Airport',
        GTF: 'Great Falls International Airport',
        GTR: 'Golden Triangle Regional Airport',
        GUC: 'Gunnison-Crested Butte Regional Airport',
        GUM: 'Guam International Airport',
        GUP: 'Gallup Municipal Airport',
        GYH: 'Donaldson Center Airport',
        GYR: 'Phoenix Goodyear Airport',
        GYY: 'Gary Regional Airport',
        HDN: 'Yampa Valley Regional Airport',
        HFD: 'Hartford-Brainard Airport',
        HGR: 'Hagerstown Regional Airport',
        HIB: 'Chisholm-Hibbing Airport',
        HII: 'Lake Havasu City Airport',
        HKS: 'Hawkins Field Airport',
        HKY: 'Hickory Regional Airport',
        HLA: 'Huslia Airport',
        HLN: 'Helena Regional Airport',
        HND: 'Henderson Executive Airport',
        HNH: 'Hoonah Airport',
        HNL: 'Honolulu International Airport',
        HNM: 'Hana Airport',
        HNS: 'Haines Airport',
        HOB: 'Lea County Regional Airport',
        HOM: 'Homer Airport',
        HON: 'Huron Regional Airport',
        HOT: 'Memorial Field Airport',
        HOU: 'Hobby Airport',
        HPB: 'Hooper Bay Airport',
        HPN: 'Westchester County Airport',
        HRL: 'Valley International Airport',
        HRO: 'Boone County Airport',
        HSL: 'Huslia Airport',
        HSV: 'Huntsville International Airport',
        HTS: 'Tri-State Airport',
        HUF: 'Terre Haute International Airport',
        HUT: 'Hutchinson Municipal Airport',
        HVN: 'Tweed New Haven Regional Airport',
        HXD: 'Hilton Head Airport',
        HYA: 'Barnstable Municipal Airport',
        HYL: 'Hollis Seaplane Base',
        HYS: 'Hays Regional Airport',
        IAD: 'Washington Dulles International Airport',
        IAH: 'Bush Intercontinental Airport',
        IAN: 'Bob Baker Memorial Airport',
        ICT: 'Wichita Mid-Continent Airport',
        IDA: 'Idaho Falls Regional Airport',
        IFP: 'Laughlin/Bullhead International Airport',
        IGM: 'Kingman Airport',
        IIK: 'Kipnuk Airport',
        ILE: 'Skylark Field',
        ILG: 'New Castle Airport',
        ILI: 'Iliamna Airport',
        ILL: 'Willmar Municipal Airport',
        ILM: 'Wilmington International Airport',
        IMT: 'Iron Mountain Airport',
        IND: 'Indianapolis International Airport',
        INL: 'Falls International Airport',
        INT: 'Smith Reynolds Airport',
        IPL: 'Imperial County Airport',
        IPT: 'Williamsport Regional Airport',
        IRK: 'Kirksville Regional Airport',
        ISN: 'Sloulin Field International Airport',
        ISO: 'Kinston Regional Jetport',
        ISP: 'Macarthur Airport',
        ITH: 'Ithaca Tompkins Regional Airport',
        ITO: 'Hilo International Airport',
        IWA: 'Williams Gateway Airport',
        IWD: 'Gogebic-Iron County Airport',
        IXD: 'Olathe/New Century Aircenter Airport',
        IYK: 'Inyokern Airport',
        JAC: 'Jackson Hole Airport',
        JAN: 'Jackson-Evers International Airport',
        JAX: 'Jacksonville International Airport',
        JBR: 'Jonesboro Municipal Airport',
        JEF: 'Jefferson City Memorial Airport',
        JFK: 'John F. Kennedy International Airport',
        JHW: 'Chautauqua County/Jamestown Airport',
        JLN: 'Joplin Regional Airport',
        JMS: 'Jamestown Regional Airport',
        JNU: 'Juneau International Airport',
        JRB: 'Downtown Manhattan Heliport',
        JST: 'Johnstown-Cambria County Airport',
        JVL: 'Southern Wisconsin Regional Airport',
        JXN: 'Jackson County Airport',
        KAE: 'Kake Airport',
        KAL: 'Kaltag Airport',
        KDK: 'Kodiak Municipal Airport',
        KEB: 'English Bay Airport',
        KKA: 'Koyuk Airport',
        KLG: 'Kalskag Airport',
        KOA: 'Kona International Airport',
        KSM: 'St Mary\'s Airport',
        KTB: 'Thorne Bay Airport',
        KTN: 'Ketchikan International Airport',
        KVC: 'King Cove Airport',
        KVL: 'Kivalina Airport',
        KWT: 'Kwethluk Airport',
        LAA: 'Lamar Municipal Airport',
        LAF: 'Purdue University Airport',
        LAL: 'Lakeland Linder Regional Airport',
        LAN: 'Lansing Capital City Airport',
        LAR: 'Laramie Regional Airport',
        LAS: 'Mccarran International Airport',
        LAW: 'Lawton-Fort Sill Regional Airport',
        LAX: 'Los Angeles International Airport',
        LBB: 'Lubbock International Airport',
        LBE: 'Arnold Palmer Regional Airport',
        LBF: 'North Platte Regional Airport Lee Bird Field',
        LBL: 'Liberal Municipal Airport',
        LBX: 'Brazoria County Airport',
        LCH: 'Lake Charles Regional Airport',
        LCK: 'Rickenbacker International Airport',
        LEB: 'Lebanon Municipal Airport',
        LEX: 'Blue Grass Airport',
        LFT: 'Lafayette Regional Airport',
        LGA: 'La Guardia Airport',
        LGB: 'Long Beach Airport',
        LHD: 'Lake Hood Airport',
        LIH: 'Lihue Airport',
        LIT: 'Little Rock National Airport',
        LMT: 'Klamath Falls Airport',
        LNK: 'Lincoln Airport',
        LNS: 'Lancaster Airport',
        LNY: 'Lanai Airport',
        LPR: 'Lorain County Regional Airport',
        LRD: 'Laredo International Airport',
        LRU: 'Las Cruces International Airport',
        LSE: 'La Crosse Municipal Airport',
        LUK: 'Cincinnati Municipal Airport Lunken Field',
        LWB: 'Greenbrier Valley Airport',
        LWS: 'Lewiston-Nez Perce County Airport',
        LYH: 'Lynchburg Regional Airport/Preston Glenn Field',
        MAF: 'Midland International Airport',
        MAZ: 'Mayaquez Airport',
        MBA: 'Manokotak Airport',
        MBL: 'Manistee County-Blacker',
        MBS: 'Saginaw International Airport',
        MCC: 'Mc Clellan Airfield',
        MCE: 'Merced Municipal Airport',
        MCG: 'McGrath Airport',
        MCI: 'Kansas City International Airport',
        MCK: 'Mc Cook Regional Airport',
        MCN: 'Middle Georgia Regional Airport',
        MCO: 'Orlando International Airport',
        MCW: 'Mason City Municipal Airport',
        MDH: 'Southern Illinois Airport',
        MDM: 'Marshall Don Hunter Sr Airport',
        MDT: 'Harrisburg International Airport',
        MDW: 'Chicago Midway Airport',
        MDY: 'Henderson Field Airport',
        MEI: 'Key Field Airport',
        MEM: 'Memphis Airport',
        MFD: 'Mansfield Lahm Regional Airport',
        MFE: 'Mcallen-Miller International Airport',
        MFR: 'Medford Rogue Valley International Airport',
        MGM: 'Montgomery Regional Airport',
        MGW: 'Morgantown Municipal Airport',
        MHE: 'Mitchell Municipal Airport',
        MHK: 'Manhattan Regional Airport',
        MHT: 'Manchester Airport',
        MIA: 'Miami International Airport',
        MIE: 'Delaware County Airport',
        MIV: 'Millville Municipal Airport',
        MJX: 'Robert J. Miller Air Park',
        MKC: 'Charles B. Wheeler Downtown Airport',
        MKE: 'General Mitchell International Airport',
        MKG: 'Muskegon County Airport',
        MKK: 'Molokai Airport',
        MKL: 'Mc Kellar-Sipes Regional Airport',
        MKT: 'Mankato Regional Airport',
        MLB: 'Melbourne International Airport',
        MLI: 'Quad City International Airport',
        MLL: 'Marshall Airport',
        MLU: 'Monroe Regional Airport',
        MMH: 'Mammoth Yosemite Airport',
        MMU: 'Morristown Municipal Airport',
        MMV: 'Mc Minnville Municipal Airport',
        MNM: 'Menominee-Marinette Twin County Airport',
        MOB: 'Mobile Regional Airport',
        MOD: 'Modesto City-County Airport',
        MOT: 'Minot International Airport',
        MOU: 'Mountain Village Airport',
        MPV: 'Edward F. Knapp State Airport',
        MQI: 'Dare County Regional Airport',
        MQJ: 'Mount Comfort Airport',
        MQY: 'Smyrna Airport',
        MRI: 'Merrill Field',
        MRY: 'Monterey Peninsula Airport',
        MSL: 'Northwest Alabama Regional Airport',
        MSN: 'Dane County Regional Airport',
        MSO: 'Missoula International Airport',
        MSP: 'Minneapolis/St. Paul International Airport',
        MSS: 'Massena International Airport',
        MSV: 'Sullivan County International Airport',
        MSY: 'New Orleans International Airport',
        MTH: 'Florida Keys Marathon Airport',
        MTJ: 'Montrose Regional Airport',
        MTM: 'Metlakatla Airport',
        MTO: 'Coles County Memorial Airport',
        MUE: 'Waimea - Kohala Airport',
        MVL: 'Morrisville-Stowe State Airport',
        MVN: 'Mount Vernon Airport',
        MVY: 'Martha\'s Vineyard Airport',
        MWA: 'Williamson County Regional Airport',
        MWH: 'Grant County International Airport',
        MYR: 'Myrtle Beach Airport',
        MZJ: 'Pinal Airpark',
        N93: 'Golovin Airport',
        NEW: 'Lakefront Airport',
        NQA: 'Millington Regional Jetport',
        NUL: 'Nulato Airport',
        OAJ: 'Jacksonville/Albert J Ellis Airport',
        OAK: 'Oakland International Airport',
        OCF: 'Ocala International Airport',
        OFK: 'Karl Stefan Memorial Airport',
        OGD: 'Ogden-Hinckley Airport',
        OGG: 'Kahului Airport',
        OGS: 'Ogdensburg International Airport',
        OKC: 'Will Rogers World Airport',
        OLM: 'Olympia Airport',
        OMA: 'Eppley Airfield',
        OME: 'Nome Airport',
        ONP: 'Newport Municipal Airport',
        ONT: 'Ontario International Airport',
        OOK: 'Toksook Bay Airport',
        OQU: 'Quonset State Airport',
        ORD: 'Chicago O\'hare International Airport',
        ORF: 'Norfolk International Airport',
        ORH: 'Worcester Regional Airport',
        ORI: 'Port Lions Airport',
        ORS: 'Orcas Island Airport',
        ORV: 'Robert (Bob) Curtis Memorial Airport',
        OSH: 'Wittman Regional Airport',
        OSU: 'Ohio State University Airport',
        OTG: 'Worthington Municipal Airport',
        OTH: 'North Bend Municipal Airport',
        OTM: 'Ottumwa Industrial Airport',
        OTZ: 'Ralph Wien Memorial Airport',
        OWB: 'Owensboro-Daviess County Airport',
        OXC: 'Waterbury-Oxford Airport',
        OXR: 'Oxnard Airport',
        PAE: 'Snohomish County Airport (Paine Field)',
        PAH: 'Paducah Barkley Regional Airport',
        PBI: 'Palm Beach International Airport',
        PCW: 'Carl R Keller Field',
        PDT: 'Eastern Oregon Regional Airport At Pendleton',
        PDX: 'Portland International Airport',
        PFN: 'Panama City-Bay County International Airport',
        PGA: 'Page Municipal Airport',
        PGD: 'Charlotte County Airport',
        PGM: 'Port Graham Airport',
        PGV: 'Pitt-Greenville Airport',
        PHF: 'Newport News/Williamsburg International Airport',
        PHL: 'Philadelphia International Airport',
        PHO: 'Point Hope Airport',
        PHX: 'Phoenix Sky Harbor International Airport',
        PIA: 'Peoria Regional Airport',
        PIB: 'Hattiesburg-Laurel Regional Airport',
        PIE: 'St. Petersburg-Clearwater International Airport',
        PIH: 'Pocatello Regional Airport',
        PIR: 'Pierre Regional Airport',
        PIT: 'Pittsburgh International Airport',
        PKB: 'Mid-Ohio Valley Regional Airport',
        PLB: 'Clinton County Airport',
        PLK: 'M Graham Clark - Taney County Airport',
        PLN: 'Pellston Regional Airport',
        PMD: 'Palmdale Regional Airport',
        PNC: 'Ponca City Regional Airport',
        PNS: 'Pensacola Regional Airport',
        POU: 'Dutchess County Airport',
        PPC: 'Prospect Creek Airport',
        PPG: 'Pago Pago International Airport',
        PQI: 'Northern Maine Regional Airport',
        PQL: 'Trent Lott International Airport',
        PRB: 'Paso Robles Municipal Airport',
        PRC: 'Ernest A. Love Field Airport',
        PSC: 'Tri-Cities Airport',
        PSE: 'Mercedita Airport',
        PSG: 'Petersburg Airport',
        PSM: 'Pease International Airport',
        PSP: 'Palm Springs International Airport',
        PTH: 'Port Heiden Airport',
        PTK: 'Oakland County International Airport',
        PUB: 'Pueblo Memorial Airport',
        PUW: 'Pullman / Moscow Regional Airport',
        PVC: 'Provincetown Municipal Airport',
        PVD: 'T.F. Green Airport',
        PVU: 'Provo Municipal Airport',
        PWM: 'Portland International Jetport',
        PWT: 'Bremerton National Airport',
        RAP: 'Rapid City Regional Airport',
        RDD: 'Redding Municipal Airport',
        RDG: 'Reading Regional Airport',
        RDM: 'Roberts Field',
        RDU: 'Raleigh-Durham International Airport',
        RFD: 'Greater Rockford Airport',
        RHI: 'Rhinelander-Oneida County Airport',
        RIC: 'Richmond International Airport',
        RIW: 'Riverton Regional Airport',
        RKD: 'Knox County Regional Airport',
        RKS: 'Rock Springs-Sweetwater County Airport',
        RME: 'Griffiss Airpark',
        RMG: 'Richard B Russell Airport',
        RNO: 'Reno-Tahoe International Airport',
        ROA: 'Roanoke Regional Airport',
        ROC: 'Greater Rochester International Airport',
        ROW: 'Roswell Industrial Air Center Airport',
        RSH: 'Russian Mission Airport',
        RST: 'Rochester International Airport',
        RSW: 'Southwest Florida International Airport',
        RUT: 'Rutland State Airport',
        RWI: 'Rocky Mount-Wilson Regional Airport',
        SAF: 'Santa Fe Municipal Airport',
        SAN: 'San Diego International Airport',
        SAT: 'San Antonio International Airport',
        SAV: 'Savannah/Hilton Head International Airport',
        SAW: 'Sawyer International Airport',
        SBA: 'Santa Barbara Airport',
        SBD: 'San Bernardino International Airport',
        SBN: 'South Bend Regional Airport',
        SBP: 'San Luis County Regional Airport',
        SBY: 'Salisbury-Ocean City Wicomico Regional Airport',
        SCC: 'Deadhorse Airport',
        SCK: 'Stockton Metropolitan Airport',
        SCM: 'Scammon Bay Airport',
        SDF: 'Louisville International Airport',
        SDP: 'Sand Point Airport',
        SDY: 'Sidney-Richland Municipal Airport',
        SEA: 'Seattle/Tacoma International Airport',
        SFB: 'Orlando Sanford International Airport',
        SFO: 'San Francisco International Airport',
        SFZ: 'North Central State Airport',
        SGF: 'Springfield Branson Regional Airport',
        SGH: 'Springfield-Beckley Municipal Airport',
        SGJ: 'St Augustine Airport',
        SGU: 'St George Municipal Airport',
        SGY: 'Skagway Airport',
        SHD: 'Shenandoah Valley Regional Airport',
        SHG: 'Shungnak Airport',
        SHH: 'Shishmaref Airport',
        SHR: 'Sheridan County Airport',
        SHV: 'Shreveport Regional Airport',
        SIG: 'Fernando Luis Ribas Dominicci Airport',
        SIT: 'Sitka Rocky Gutierrez Airport',
        SJC: 'San Jose International Airport',
        SJT: 'San Angelo Regional Airport/Mathis Field',
        SJU: 'Luis Munoz Marin International Airport',
        SKX: 'Taos Regional Airport',
        SLC: 'Salt Lake City International Airport',
        SLE: 'Salem Municipal Airport - McNary Field',
        SLK: 'Adirondack Regional Airport',
        SLN: 'Salina Municipal Airport',
        SMF: 'Sacramento International Airport',
        SMX: 'Santa Maria Public Airport',
        SNA: 'John Wayne Airport',
        SNP: 'Saint Paul Island Airport',
        SOP: 'Moore County Airport',
        SOV: 'Seldovia Airport',
        SOW: 'Show Low Regional Airport',
        SPI: 'Abraham Lincoln Capital Airport',
        SPS: 'Wichita Falls Municipal Airport',
        SQI: 'Whiteside County Airport',
        SRQ: 'Sarasota-Bradenton International Airport',
        SRR: 'Sierra Blanca Regional Airport',
        STC: 'St Cloud Regional Airport',
        STJ: 'Rosecrans Memorial Airport',
        STL: 'Lambert-St. Louis International Airport',
        STP: 'St Paul Downtown Airport / Holman Field',
        STS: 'Sonoma County Airport',
        STT: 'Cyril E King Airport',
        STX: 'Henry E Rohlsen Airport',
        SUN: 'Friedman Memorial Airport',
        SUS: 'Spirit Of St Louis Airport',
        SUX: 'Sioux Gateway Airport',
        SVA: 'Savoonga Airport',
        SVC: 'Grant County Airport',
        SWF: 'Stewart International Airport',
        SWO: 'Stillwater Regional Airport',
        SYR: 'Syracuse Hancock International Airport',
        T44: 'Trident Basin Seaplane Base',
        TAL: 'Ralph M Calhoun Memorial Airport',
        TBN: 'Waynesville Regional Airport At Forney Field',
        TCL: 'Tuscaloosa Regional Airport',
        TEB: 'Teterboro Airport',
        TEX: 'Telluride Regional Airport',
        TIX: 'Space Coast Regional Airport',
        TLH: 'Tallahassee Regional Airport',
        TLT: 'Tuluksak Airport',
        TNI: 'Tinian International Airport',
        TOG: 'Togiak Airport',
        TOL: 'Toledo Express Airport',
        TPA: 'Tampa International Airport',
        TPL: 'Draughon-Miller Central Texas Regional Airport',
        TRI: 'Tri-Cities Regional Airport',
        TTN: 'Trenton Mercer Airport',
        TUL: 'Tulsa International Airport',
        TUP: 'Tupelo Regional Airport',
        TUS: 'Tucson International Airport',
        TVC: 'Cherry Capital Airport',
        TVF: 'Thief River Falls Regional Airport',
        TVL: 'Lake Tahoe Airport',
        TVR: 'Vicksburg Tallulah Regional Airport',
        TWF: 'Magic Valley Regional Airport',
        TXK: 'Texarkana Regional Airport',
        TYR: 'Tyler Pounds Regional Airport',
        TYS: 'Mcghee Tyson Airport',
        UCA: 'Oneida County Airport',
        UIN: 'Quincy Regional Airport - Baldwin Field',
        UNK: 'Unalakleet Airport',
        UNV: 'University Park Airport',
        UOX: 'University-Oxford Airport',
        UUU: 'Newport State Airport',
        VAK: 'Chevak Airport',
        VCT: 'Victoria Regional Airport',
        VCV: 'Southern California Logistics Airport',
        VDZ: 'Valdez Pioneer Field',
        VGT: 'North Las Vegas Air Terminal',
        VIS: 'Visalia Municipal Airport',
        VLD: 'Valdosta Regional Airport',
        VPS: 'Fort Walton Beach Airport',
        VPZ: 'Porter County Municipal Airport',
        VQQ: 'Cecil Field Airport',
        VQS: 'Vieques Airport',
        VRB: 'Vero Beach Municipal Airport',
        WBB: 'Stebbins Airport',
        WDG: 'Woodring Municipal Airport',
        WLK: 'Selawik Airport',
        WNA: 'Napakiak Airport',
        WRG: 'Wrangell Airport',
        WRL: 'Worland Municipal Airport',
        WST: 'Westerly State Airport',
        WTK: 'Noatak Airport',
        WWD: 'Cape May County Airport',
        WYS: 'West Yellowstone Airport',
        X44: 'Miami Airport',
        X95: 'Diego Jimenez Torres Airport',
        XNA: 'Northwest Arkansas Regional Airport',
        YAK: 'Yakutat Airport',
        YKM: 'Yakima Air Terminal/Mcallister Field',
        YKN: 'Chan Gurney Municipal Airport',
        YNG: 'Youngstown Regional Airport',
        YUM: 'Yuma International Airport',
        Z08: 'Ofu Airport',
        Z09: 'Kasigluk Airport'
         }
    }

    searchFlights(flightsMap, selectedFlight) {
        let origin = selectedFlight.origin;
        let dest = selectedFlight.dest;
        let originFlights = flightsMap[origin];
        if(!originFlights) {
            return [];
        }
        
        return originFlights.filter(flight => flight.dest === dest);
    }

    getFlightsAsArray(flightsMap) {
        if(!flightsMap){
          return [];
        }
        let flightsArray = [];
        // can use lodash to reduce the logic
        let keys = Object.keys(flightsMap);
        for(let i = 0 ; i < keys.length ; i ++ ) {
            flightsArray = flightsArray.concat(flightsMap[keys[i]]);
        }
        return flightsArray;
    }

    getFlightsStates(flightsMap) {
        if(!flightsMap) {
            return [];
        }
        let flightsStates = {};
        let keys = Object.keys(flightsMap);
        keys.forEach(key => {
            flightsStates[key] = true;
            let flights = flightsMap[key];
            flights.forEach(flight => {
                flightsStates[flight.dest] = true;
            });
        });
        return Object.keys(flightsStates).map(state => ({name:state, realName: this.airportRealNames[state]}));
    }

    /// return flight delays as an array ///
    getFlightDelays(flights) {
      return flights.map(function(flight) {
        return flight.arrivalDelay;
      });
    }

    getFlightDates(flights) {
      return flights.map(function(flight) {
        return flight.date;
      });
    }
    getFlightsDatesAndDelays(flights) {
        return flights.map(function(flight) {
            return {
                date: Date.parse(flight.date),
                delay: flight.arrivalDelay,
                departureTime: flight.departureTime,
                arrivalTime: flight.arrivalTime,
                elapsedTime: flight.elapsedTime
            };
          });
    }

    getFlightUniqeDates(flightsDates) {
      let dateMap = {};
      for (let i = 0; i < flightsDates.length; i++){
          dateMap[flightsDates[i]] = true;
      }
      return Object.keys(dateMap);
    }

    getFlightDelaysRatio(flights) {
      return flights.map(function(flight) {
            let flightDelayRatio = Math.ceil((flight.arrivalDelay / flight.elapsedTime) * 100);
        return flightDelayRatio;
      });
    }

    getOverallDelayRatio(flights) {  
        let avg = 0.0;
        for(let i = 0 ; i < flights.length; i ++ ) {
            let flightDelayRatio = (flights[i].arrivalDelay / flights[i].elapsedTime) * 100;
            avg += flightDelayRatio / flights.length;
        }
        return avg.toFixed(2);
      }

    getCorrelationPoints(flights) {
      let flightDistanceMap = {};
      flights.forEach(function(flight) {
          if(!flightDistanceMap[flight.distance]){
              
              flightDistanceMap[flight.distance] = {
                  sum: 0,
                  count: 0
              };
          }
          flightDistanceMap[flight.distance].sum += flight.arrivalDelay;
          flightDistanceMap[flight.distance].count ++;

      })
      let correlationPoints = [];
      let keys = Object.keys(flightDistanceMap);
      for(let i = 0 ; i < keys.length ; i ++ ) {
          let distance = keys[i];
          let avgDelayas = flightDistanceMap[distance].sum / flightDistanceMap[distance].count;
          correlationPoints.push({x: parseFloat(distance), y: avgDelayas});
      }
      return correlationPoints;
    }
    
    recommendFlights(__flights__) {
        // recommendation based on minumum delays
        let myFlights = [...__flights__];
        /* eslint-disable no-console */
/* eslint-enable no-console */
        let getMinumum = (flights, len) => {
            let mini = {};
            let minIdx = -1;
            for(let i = 0 ; i < len; i ++) {
                if(mini.arrivalDelay) {
                    if(mini.arrivalDelay > flights[i].arrivalDelay) {
                        mini = flights[i];
                        minIdx = i;
                    }
                }else {
                    mini = flights[i];
                    minIdx = i;
                }
            }
            return {index: minIdx, value: mini};
        };
        let swap = (flights, i, j) => {
            let tmpFlight = flights[i];
            flights[i] = flights[j];
            flights[j] = tmpFlight;
        }
        
        let minimum = getMinumum(myFlights, myFlights.length);
        swap(myFlights, minimum.index, myFlights.length - 1);

        minimum = getMinumum(myFlights, myFlights.length - 1);
        swap(myFlights, minimum.index, myFlights.length - 2);

        minimum = getMinumum(myFlights, myFlights.length - 2);
        swap(myFlights, minimum.index, myFlights.length - 3);

        
        return [myFlights[myFlights.length - 1], myFlights[myFlights.length - 2], myFlights[myFlights.length - 3]];
    }
}

export default FlightsService;